version: '3.8'

services:
  chat:
    image: chat-service
    build:
      dockerfile: Dockerfile
      context: ../
    container_name: chat
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure

  db:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
      POSTGRES_INITDB_ARGS: -A md5
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all